### PR TITLE
master <- trunk

### PR DESCRIPTION
**Pull request by hisahi**
### Short description
Completed in trunk:
* #759: The review of previous week should have line breaks when it's shown in ReviewStudent page
* #755: Improve massive email
* #749: Improve tags
* #742: Remove redundant course import button
* #744: Project info is visible when editing it (name, repository)
* #754: Improve dropped out students list in course page
* #760: Improve persistent state
* #745: Change "course is active" to "active registration" throughout
* #741: Spacing for various components on the course page
* #751: Improve modify selected students UI in the course page
* #748: Redundant period in course lists should be removed
* #756: Improve previous participation
* #768: Use repository address as a link
* #758: Improve BrowseReviews UI
* #761: Maximum point of each week should be shown to students
* #785: Fix the bug that the Add comment-accordion cannot be opened in BrowseReviews-page
* #752: Show a review button instead of minus if there is no review in the current week in course page

### DoD
I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [x] documented the code or added documentation to the wiki.
- [x] added or modified test(s).
- [x] test(s) that actually pass.
- [x] works in trunk branch

### CODE REVIEW

**Comment by gotonode** [comment]
Should all team members review this and approve? Would that be a good idea? At least it would keep us updated on what's happening. ☺

**Comment by gotonode** [comment]
Seems fine.

For the email, how about a test email server? From the same server to itself or to another test server?

**Comment by hisahi** [comment]
#791 should be fixed in trunk before merging

**Comment by gotonode** [comment]
I haven't done this yet. Can I do the honors? It seems everyone agrees. Is within a few hours now okay?

**Comment by hisahi** [comment]
This should be merged today, if possible.

**Comment by gotonode** [comment]
Is merging okay if tests pass? I'm currently on mobile. Does that raise an issue? I can merge but cannot do anything else at the moment. I belive each team member should merge trunk to master at least once. ☺

**Pull request merged**
