### PR TITLE
trunk -> master

### PR DESCRIPTION
**Pull request by hisahi**
### Short description
* Refactoring
* #607: remove redundant periods in MyPage and course listing (#681)
* #661: Make user log in in case of invalid session
* #573: Modify email message; add 'Send a copy to all instructors' (#684)
* #674: Code review random assign: do not assign repositories by dropped students
* #672: Instructor and tag dropdown should float over scrollable area
* #372: Prefill github field with https://github.com/ when user registers his project

### DoD
I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [x] documented the code or added documentation to the wiki.
- [x] added or modified test(s).
- [x] test(s) that actually pass.
- [x] works in trunk branch

### CODE REVIEW

**Comment by gotonode** [comment]
What's the protocol here?

**Comment by hisahi** [comment]
Checks must pass, trunk must be tested, 1 review approval if possible

**Comment by gotonode** [comment]
You mean in staging; manually and thoroughly?

**Comment by gotonode** [comment]
Perhaps merge this tomorrow during meeting?

**Comment by hisahi** [comment]
Staging involves manual testing. I have tested this some and haven't found any issues. Merging tomorrow could also be a possibility.

**Pull request merged**
