### PR TITLE
Move send email and CSV export buttons under "Student tools"

### PR DESCRIPTION
**Pull request by Mamelukki**
### Short description
#894 Moved CSV export and send email buttons under "Student tools" and modified the look of the tool, so that it's more compact and descriptive

### DoD
I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [ ] documented the code or added documentation to the wiki.
- [x] added or modified test(s).
- [x] test(s) that actually pass.

### CODE REVIEW

**Comment by gotonode** [comment]
Looks good and clears up the student table nicely!

I'll accept the changes.

**Comment by gotonode** [comment]
Once that is changed, I can approve again and/or merge.

**Comment by Mamelukki** [comment]
Thanks for the feedback, I will change it back. Should I still keep the amount of selected students after the modify selected students header or just take it away and only keep it in the accordion header?

**Comment by hisahi** [comment]
I would probably add "student" / "students" to the "selected" counter, since it isn't clear what it is referring to right now.

**Comment by hisahi** [comment]
Other than that, LGTM

**Comment by hisahi** [comment]
I was referring to changing the text, not adding the counter elsewhere, so that instead of "0 selected" => "0 students selected", "1 selected" => "1 student selected", etc.

**Comment by Mamelukki** [comment]
Oh yes, true. Sorry, I misread. How to make it so that if there is only one student selected, it shows just "student" instead of "students"?

**Comment by hisahi** [comment]
> Oh yes, true. Sorry, I misread. How to make it so that if there is only one student selected, it shows just "student" instead of "students"?

You can check if we only have one student selected and then use a ternary `?:` for it.

**Comment by gotonode** [comment]
Looks good, will merge!

**Pull request merged**
