### PR TITLE
Tags can be associated with a course

### PR DESCRIPTION
**Pull request by hisahi**
### Short description
#440, also #908

### DoD
I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [x] documented the code or added documentation to the wiki.
- [x] added or modified test(s).
- [x] test(s) that actually pass.

### CODE REVIEW

**Comment by yumoL** [comment]
Would it be better to have a short instruction somewhere in the manageTags page to tell the user how to add a tag from global tags to course tags? There's no course tag in the beginning and it may be more intuitive if there's an instruction

**Comment by hisahi** [comment]
That is probably unnecessary for two reasons:

1. it is fairly simple to understand how that is done; you choose one of the global tags, uncheck the box and save it, which turns it into a course tag.
2. the instruction probably won't be relevant after a while once all tags are either course or global tags (the actual process to get used to that will take some time, sure), and after that tags will only need to be rarely moved between being course-specific and global.

It's surely possible to display an instruction like that when there are no course tags, but again, the question of whether that is necessary (or wanted) is a separate matter, and I'm not fully convinced that is needed.

**Comment by hisahi** [comment]
I'll add some kind of instructions real quick after all

**Comment by yumoL** [comment]
Not sure if I did something wrong or it's a bug: I selected a global tag and converted it into to course tag, then I created a new tag without the Global-field checked and the first tag which I converted from the global tags just disappeared

**Comment by hisahi** [comment]
> Not sure if I did something wrong or it's a bug: I selected a global tag and converted it into to course tag, then I created a new tag without the Global-field checked and the first tag which I converted from the global tags just disappeared

It probably kept the converted tag so that you could edit it again. Did you press "I want to create a new tag"?

**Comment by yumoL** [comment]
> > Not sure if I did something wrong or it's a bug: I selected a global tag and converted it into to course tag, then I created a new tag without the Global-field checked and the first tag which I converted from the global tags just disappeared
> 
> It probably kept the converted tag so that you could edit it again. Did you press "I want to create a new tag"?

I forgot to press the create new tag-button, my problem.

**Comment by yumoL** [comment]
Here's another question, in #440 it's said that it's not user-friendly to show all tags when selecting a tag to a student, would we like to just show the course tags or all the tags including global tags in the tag dropdown in the course page?

**Pull request merged**
