### PR TITLE
feat/add_document_title

### PR DESCRIPTION
**Pull request by mjaakko**
### Short description

#940 `react-helmet` is used to add document title for each page

### DoD

I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [ ] documented the code or added documentation to the wiki.
- [ ] added or modified test(s).
- [x] test(s) that actually pass.
- [x] works in trunk branch

### CODE REVIEW

**Comment by hisahi** [comment]
My suggestions (for teacher view)

* BrowseReviews: {student name} - {course ohid} - Labtool
* ReviewStudent: Review Week N - {student name} - Labtool
* CoursePage: {course name} - Labtool
** ModifyCourseInstancePage: same as above
** ModifyCourseInstanceStaff: Assistants - {course name} - Labtool
** ModifyCourseinstanceCodeReviews: Code Reviews - {course name} - Labtool
** CreateChecklist: Checklists - {course name} - Labtool
** ManageTags: Tags - {course name} - Labtool

My suggestions (for student view)

* CoursePage: {course name} - Labtool

**Comment by gotonode** [comment]
The client wanted "2.0" to be removed from "Labtool 2.0".

**Comment by gotonode** [comment]
Should this have a more descriptive title?

**Comment by hisahi** [comment]
Perhaps "Edit course" should also be in the title for ModifyCourseInstance?

**Comment by hisahi** [comment]
The review code review title is also fairly generic right now

**Pull request merged**
