### PR TITLE
Added two empty spaces

### LINKED ISSUE #654: Add missing space to My Page
A single space is missing. Easy fix.

### PR DESCRIPTION
**Pull request by gotonode**
Added two empty spaces.

Fixes #654.

### CODE REVIEW

**Comment by yumoL** [comment]
Snapshots should be also updated?

**Comment by gotonode** [comment]
Can you refer that code for me?

**Comment by gotonode** [comment]
Yes I'll update them.

**Comment by gotonode** [comment]
Do you know in what format they need to be typed in? I get that it's quite exact.

I'll check back on this when I have time today or tomorrow.

**Comment by yumoL** [comment]
You don't need to type anything manually, running `npm test -- -u` would be enough. 
[Please check here](https://github.com/UniversityOfHelsinkiCS/labtool/wiki/Running-tests)

**Comment by gotonode** [comment]
Thank you! I had forgotten about this. I'll do that when I have the time, today or tomorrow.

**Comment by gotonode** [comment]
It seems that someone beat me to it. 😅

I'll however do it again for myself, for learning purposes.

**Comment by gotonode** [comment]
Merged. ☺

**Pull request merged**
