### PR TITLE
Subchecklists (check prerequisites)

### PR DESCRIPTION
**Pull request by hisahi**
### Short description
#956

### DoD
I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [x] documented the code or added documentation to the wiki.
- [x] added or modified test(s).
- [x] test(s) that actually pass.

### CODE REVIEW

**Comment by hisahi** [comment]
This will require further planning and won't be finished this sprint

**Comment by hisahi** [comment]
> One bug I noticed is that when selecting a prerequisite for a category, items from the category can be selected. This is not necessarily a problem as they cannot be saved that way, but it would be better for usability if they were hidden from the dropdown.
> 
If you select a prerequisite for a category that is in that category, that check will have no prerequisite set for it.

> Also, creating new items to a category will not set prerequisite by default for them if category has a prerequisite selected.
> 
The prerequisite only applies to existing checks - perhaps it is a good idea to make it apply to new ones, too.

> Not sure if this is intended behavior, but on review week page checklist items that are hidden are still visible in the text that can be copied to the review.
> 
To my knowledge, they should be, but the client should be asked about that.

**Comment by mjaakko** [comment]
> If you select a prerequisite for a category that is in that category, that check will have no prerequisite set for it.

This does not seem to work for new checks that are added.

**Comment by hisahi** [comment]
> 
> 
> > If you select a prerequisite for a category that is in that category, that check will have no prerequisite set for it.
> 
> This does not seem to work for new checks that are added.

Right now, the category prerequisites only apply for existing checks in that category.

**Comment by mjaakko** [comment]
> > > If you select a prerequisite for a category that is in that category, that check will have no prerequisite set for it.
> > 
> > 
> > This does not seem to work for new checks that are added.
> 
> Right now, the category prerequisites only apply for existing checks in that category.

This bug happens when a checklist has items A and B in category X. Then if item C is added to category X and C is selected as prerequisite for category X, C will also have C as prerequisite. This might be confusing as selecting A as prerequisite for category X would not set A as prerequisite for A.

**Comment by hisahi** [comment]
> 
> 
> > > > If you select a prerequisite for a category that is in that category, that check will have no prerequisite set for it.
> > > 
> > > 
> > > This does not seem to work for new checks that are added.
> > 
> > 
> > Right now, the category prerequisites only apply for existing checks in that category.
> 
> This bug happens when a checklist has items A and B in category X. Then if item C is added to category X and C is selected as prerequisite for category X, C will also have C as prerequisite. This might be confusing as selecting A as prerequisite for category X would not set A as prerequisite for A.

In that case, it is a bug which should also be fixed.

**Pull request merged**
