### PR TITLE
Move the point total closer to the user's name

### PR DESCRIPTION
**Pull request by gotonode**
Implements #949.

### CODE REVIEW

**Comment by gotonode** [comment]
I might schedule this for next week, since it's of no particular priority. I'll fiddle around with the specific section while I'm at it, with accessibility in mind.

**Comment by hisahi** [comment]
The change is to WeekReviews to remove the existing total points, and then add them to StudentInfo.

**Comment by hisahi** [comment]
> 
> 
> I might schedule this for next week, since it's of no particular priority. I'll fiddle around with the specific section while I'm at it, with accessibility in mind.

The priority for this is falrly high and was to my knowledge somewhat high in the original sprint backlog

**Comment by hisahi** [comment]
I did some initial changes, but TotalPoints isn't currently really visible and needs more emphasis

**Comment by gotonode** [comment]
Also accessibility should be kept in mind. Simply put, does it look good and representable? Is the data easy to find for all (possible) users? Can the user understand what the data is in relation to? Is there something near that would cause it to be associated to something it's not supposed to be associated with. Things like these.

**Comment by hisahi** [comment]
I don't think there are any other accessibility issues other than the fact that it's not easy to find right now, so it needs more emphasis, such as a color, etc.

**Pull request merged**
