### PR TITLE
Double the size of the margins

### PR DESCRIPTION
**Pull request by gotonode**
Implements #954.

### CODE REVIEW

**Comment by gotonode** [comment]
This covers all pages.

**Comment by gotonode** [comment]
File `index.css` now contains:

```css
body {
  margin: 0 10px;
  padding: 0;
  font-family: sans-serif;
}
```

I think the client only wanted margins on the left and right sides, not at the top. Does this amount of additional margin feel right for you?

**Comment by mjaakko** [comment]
I think the point of issue #954 was to add margins to places where UI elements are too close to each other, e.g. modify checklists page

**Comment by gotonode** [comment]
I'll implement the first idea (global margins) and then the client can have the final word.

**Comment by mjaakko** [comment]
> I'll implement the first idea (global margins) and then the client can have the final word.

This was discussed in previous meeting: https://docs.google.com/document/d/18f_bjgGQChfvBTYYj_ZNWPgOa9Dp8jRbj1_705lS-tk/edit

**Comment by gotonode** [comment]
I'll add the necessary margins next week.

**Comment by gotonode** [comment]
This is actually a common accessibility issue. Developers often overlook the form when focusing on the functionality. Both are needed for proper accessibility.

**Comment by hisahi** [comment]
Any other spacing issues?

**Comment by gotonode** [comment]
I'll go this over soon, this week the latest. I've read some accessibility manuals and will keep those in mind while doing so. Elements shouldn't be too clumped up together; nor should they be too far apart. It's basically a balancing issue.

**Comment by gotonode** [comment]
Is the edit/modify checklists page already conforming to the new margin rules? Since it has received some changes this sprint.

**Comment by gotonode** [comment]
What I think we ought to do is merge this PR and consider the margins when doing other edits to the elements in the future. It's an accessibility issue.

Unless someone wants to make some changes now.

**Pull request merged**
