### PR TITLE
Improve next week button

### PR DESCRIPTION
**Pull request by gotonode**
Now it is just an arrow with a tooltip. It'll also ask the user to confirm his/her choice to advance the course by 1 week.

### CODE REVIEW

**Comment by gotonode** [comment]
Yes, of course. I just negated the logic because I wanted the constant to be called `weekAdvanceEnabled` instead of `weekAdvanceDisabled`.

**Comment by gotonode** [comment]
My bad. Was supposed to be `pointer`. Will fix.

**Comment by hisahi** [comment]
The issue is that it's useful when the button is disabled, so I would use `auto` or `not-allowed`.

**Comment by gotonode** [comment]
The `not-allowed` seems quite rude but it certainly works.

This okay now?

```jsx
<Popup
  content={weekAdvanceEnabled ? 'Advance course by 1 week' : 'Already at final week'}
  trigger={<Icon disabled={!weekAdvanceEnabled} name="right arrow" onClick={() => moveToNextWeek()} style={{ marginLeft: '15px', cursor: weekAdvanceEnabled ? 'pointer' : 'not-allowed' }} />}
/>
```

**Comment by hisahi** [comment]
Seems ok

**Pull request merged**
