### PR TITLE
Show less stats when they are not needed

### PR DESCRIPTION
**Pull request by gotonode**
Implements #851.

### CODE REVIEW

**Comment by gotonode** [comment]
Now we always show how many students are active on the course (0, 1 or more). In addition, if the course has at least 1 dropped student, we show their amount as well as the total number of students (dropped plus active).

**Comment by gotonode** [comment]
Yes, absolutely. It'll look much better. I'll make the change later.

**Comment by gotonode** [comment]
The current code is as follows:

```js
<p>
  {activeStudentCount} active student{activeStudentCount === 1 ? '' : 's'}
  {droppedStudentCount > 0 ? ', ' + droppedStudentCount + ' dropped (' + totalStudentCount + ' in total)' : ''}
</p>
```

Okay now?

**Comment by hisahi** [comment]
`', ' + droppedStudentCount + ' dropped (' + totalStudentCount + ' in total)'`
could still be a template

**Comment by gotonode** [comment]
I tried the following but it didn't parse it correctly:

```js
<p>
  {activeStudentCount} active student{activeStudentCount === 1 ? '' : 's'}
  {droppedStudentCount > 0 ? ', ${droppedStudentCount} dropped (${totalStudentCount} in total)' : ''}
</p>
```

It just shows the raw variables with the dollar symbol.

**Comment by gotonode** [comment]
Okay, now I remember and I do feel silly now. Updating.

**Pull request merged**
