### PR TITLE
checkboxes & bulk assign

### PR DESCRIPTION
**Pull request by hisahi**
### Short description
#669 Checkbox for student table to bulk assign

### DoD

I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [x] documented the code or added documentation to the wiki.
- [x] added or modified test(s).
- [x] test(s) that actually pass.

### CODE REVIEW

**Comment by yumoL** [comment]
We don't have any tests here?

**Comment by hisahi** [comment]
> We don't have any tests here?

I suppose it could be tested seeing we can select students by supplying different props.

**Comment by hisahi** [comment]
> 
> 
> Maybe the dropped status should also be selected using a dropdown menu:
> image
> 
> Other than that, looks good to me

Using a dropdown requires another variable in the state, and as there will only ever be two options, it seems superfluous to have a dropdown just to make the UI look more consistent.

**Comment by mjaakko** [comment]
> > Maybe the dropped status should also be selected using a dropdown menu:
> > image
> > Other than that, looks good to me
> 
> Using a dropdown requires another variable in the state, and as there will only ever be two options, it seems superfluous to have a dropdown just to make the UI look more consistent.

Alright, that's reasonable

**Comment by hisahi** [comment]
I will probably implement a test for these later, but I will merge this for now

**Pull request merged**
