### PR TITLE
Advance-button should have text & no confirmation

### PR DESCRIPTION
**Pull request by gotonode**
Implements #831.

### CODE REVIEW

**Comment by gotonode** [comment]
It won't ask for confirmation since it's very easy to go back when needed.

**Comment by gotonode** [comment]
You can also go past 1 week, for code review purposes.

**Comment by gotonode** [comment]
Two questions. Does anyone know how to have some spacing between the icon and the text without modifying the text to include a whitespace character? Also, once the button inside the ``Popup`-element is disabled, the `Popup` won't show its tooltip or change the mouse cursor accordingly.

**Comment by hisahi** [comment]
Skipping to "Final week" is now done by #929.

**Comment by gotonode** [comment]
I was thinking that as well, just now. Will remove the necessary part.

**Comment by hisahi** [comment]
> 
> 
> Two questions. Does anyone know how to have some spacing between the icon and the text without modifying the text to include a whitespace character? Also, once the button inside the `Popup`-element is disabled, the `Popup` won't show its tooltip or change the mouse cursor accordingly.

Popup doesn't work for disabled buttons; that is a well known issue, and usually requires a bit of a workaround to make it work. As for spacing, adding whitespace is the easiest solution.

Right now the problem is that the button isn't centered.

**Comment by gotonode** [comment]
I'm aligning it at the center with:

```js
<Table.Cell textAlign="center">
  Current week: {selectedInstance.currentWeek}
```
It doesn't seem to take into account the button that is inside the popup. The text aligns well, I think. But the button is ignored.

**Comment by gotonode** [comment]
Now the button looks much better! I was thinking that it was too high as well. After all, it shouldn't be too prominent.

**Comment by gotonode** [comment]
It still doesn't look to be at the right horizontal position, though.

**Comment by hisahi** [comment]
Now that I think of it, I'm not sure if there is much to do regarding that

**Comment by gotonode** [comment]
Shall I remove WIP and we'll see if the client says anything? This doesn't seem to be a big issue.

**Comment by hisahi** [comment]
Sure

**Pull request merged**
