### PR TITLE
Add course import to frontend

### PR DESCRIPTION
**Pull request by hisahi**
### Short description
This adds course import capability to the frontend (#513).

### DoD
I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [x] documented the code or added documentation to the wiki.
- [x] added or modified test(s).
- [x] test(s) that actually pass.

### CODE REVIEW

**Comment by gotonode** [comment]
But the comments in code ought to be in English.

**Comment by hisahi** [comment]
> But the comments in code ought to be in English.

All of the comments I wrote are in English. The new urki-simulation files are simply copies of existing files which I did not change the contents of.

**Comment by gotonode** [comment]
For me, Travis is showing "build in progress". Did it get stuck? Need a reset?

**Comment by hisahi** [comment]
Works if you open the Travis page, so it's probably a temporary problem at either Travis' or GitHub's end.

**Comment by gotonode** [comment]
So if someone else reviews this, it can be merged?

**Comment by hisahi** [comment]
Should be fine to merge when reviewed.

**Pull request merged**
