### PR TITLE
"Final week" for advance, final review highlight

### PR DESCRIPTION
**Pull request by hisahi**
### Short description
#909
It's not in the dropdown (#835); that is for #844

### DoD
I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [ ] documented the code or added documentation to the wiki.
- [x] added or modified test(s).
- [x] test(s) that actually pass.

### CODE REVIEW

**Comment by gotonode** [comment]
Should this be merged before #843? I still need to figure and fine-tune that PR somewhat.

**Comment by hisahi** [comment]
> 
> 
> Should this be merged before #843? I still need to figure and fine-tune that PR somewhat.

That is fine, it just needs approval.

**Comment by hisahi** [comment]
I don't think this properly merged

**Comment by gotonode** [comment]
I noticed this as well.

**Comment by gotonode** [comment]
And I thought this might happen. Did #843 merge and will you be merging this one now?

**Comment by hisahi** [comment]
Seemed to merge fine

**Pull request merged**
