### PR TITLE
master <- trunk

### PR DESCRIPTION
**Pull request by hisahi**
### Short description
* #952: Rename "non-dropped" to "active" on mass email page
* #947: Course title is a link on review page
* #950: Hourglass shows instead of points on course page
* #914: Add "edit code reviews" button to course page
* #957: Only show "send email notification" on latest comment, unless we already sent one
* #948: CSV, separate first and last names, add instructor
* #951: Only show two decimals on review page
* #953: Make "total max points" more intuitive on checklist creation
* #981: The "invalid registration" should be changed to "mistaken registration"
* #894: Move email send and CSV export buttons somewhere more visible
* #962: Only one checklist for all code reviews
* #974: Scrolling fixes on Chrome
* #983: The first tag should not be chosen automatically into the editing tag form when go to the modifyTag page
* #991: Disable dropdowns if no students are selected
* #767: Minimum requirement in checklists
* #940: Add page titles to each page
* #982: Gitlab repository should not be checked when using github api
* #980: Only the local tag should be shown in the student table
* #994: Fix issue checking bugs

### DoD
I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [x] documented the code or added documentation to the wiki.
- [x] added or modified test(s).
- [x] test(s) that actually pass.
- [x] works in trunk branch

### CODE REVIEW

**Comment by gotonode** [comment]
I have tested most of these manually (but separately). Do any of these components have major interplay between them that we should be aware of?

**Comment by hisahi** [comment]
Probably not, but you never know - it's worth testing the trunk at least locally or perhaps even in staging. There are no migrations that I know of though, so it might be fine to merge this as-is

**Comment by gotonode** [comment]
Can add #973 to this.

**Comment by hisahi** [comment]
The migration will probably need some extra testing, preferably on staging. I did test it locally though

**Comment by gotonode** [comment]
Is there any benefit in testing these changes locally versus testing them solely on staging?

**Comment by hisahi** [comment]
Local is easier to test if/when something goes wrong, but staging is generally a better and more faithful testing env

**Comment by hisahi** [comment]
There are some bugs that need to be fixed first:
* trailing / breaks GitHub repo check
* removing GitHub warning fails due to backend giving a 403

**Pull request merged**
