### PR TITLE
Empty comments cannot be added

### LINKED ISSUE #608: Instructor or student should not be able to add empty comments

### PR DESCRIPTION
**Pull request by gotonode**
This fixes #608.

WIP!

### CODE REVIEW

**Comment by hisahi** [comment]
The check is now also after Comment.create when it should be before.

**Comment by gotonode** [comment]
True!

How about this instead?

```js
comment.comment.trim().length === 0
````

So creating a comment object automatically saves it somewhere? Because my thinking was that it creates it (only in memory), and then it can be easily verified and discarded if something's wrong. But I also see the point in not creating objects when the data to be put into them is not there.

**Comment by hisahi** [comment]
Checking length also works. It's also possible to simply do a truthiness check, as an empty string is falsy while a string containing anything is truthy.

Calling `await Comment.create` (and similarly for any other model) will create it and save it in the database, as the function returns the created object (for purposes such as checking the ID generated automatically by the database or the ORM).

**Comment by gotonode** [comment]
Yes I remember now. I think I prefer the length check over truth value check. Fixed.

**Pull request merged**
