### PR TITLE
Change "Current week" to a dropdown

### PR DESCRIPTION
**Pull request by gotonode**
Implements #835.

### CODE REVIEW

**Comment by hisahi** [comment]
also needs a "Final Week" option for weekAmount + 1

**Comment by gotonode** [comment]
Final week option was implemented earlier. This PR just implements the dropdown.

**Comment by hisahi** [comment]
> Final week option was implemented earlier. This PR just implements the dropdown.

Yes, but it still must be included in the dropdown options

**Comment by gotonode** [comment]
Why doesn't the dropdown show its options?

**Comment by hisahi** [comment]
options cannot just be numbers

**Comment by hisahi** [comment]
It should include weekAmount, so `<=` and not `<`

**Comment by gotonode** [comment]
This seems to be almost complete now.

One issue is that if the current week is set to Final Review, and then that option is unchecked, the week remains at that week. It should be decremented by 1 in this case.

**Comment by hisahi** [comment]
> This seems to be almost complete now.
> 
> One issue is that if the current week is set to Final Review, and then that option is unchecked, the week remains at that week. It should be decremented by 1 in this case.

I would suggest resetting the value to null/undefined instead, although something like that should happen automatically

**Comment by gotonode** [comment]
It does, but when going back to the course page, it still says Final Review.

**Comment by hisahi** [comment]
> > This seems to be almost complete now.
> > One issue is that if the current week is set to Final Review, and then that option is unchecked, the week remains at that week. It should be decremented by 1 in this case.
> 
> I would suggest resetting the value to null/undefined instead, although something like that should happen automatically

And it does. If I set the week to Final Review and then disable the final review, the dropdown blanks out and then the user must choose another week. Is this not the correct behavior?

**Comment by gotonode** [comment]
But if the user doesn't choose anything and saves the form, check what happens on the course page. It stays on Final Review despite it not being available for the course.

**Comment by gotonode** [comment]
The "required" attribute isn't working right?

**Comment by gotonode** [comment]
Also, when editing the course's details with the phantom Final Review week active, the Current Week dropdown is empty. I don't think it ever should be empty.

**Comment by gotonode** [comment]
I feel this is complete now. GJ!

**Pull request merged**
