### PR TITLE
Fix/more intuitive to set max points for a week in checklist

### PR DESCRIPTION
**Pull request by yumoL**
### Short description

#953 Setting max points for a week when modifying a checklist is more intuitive.
Also, change the background of topic cards so that they can be seprarated more easily from each other. 
### DoD

I have:
- [x] added actual code.
- [x] produced clean code that passes ESLint.
- [x] code that actually does what it should.
- [ ] documented the code or added documentation to the wiki.
- [x] added or modified test(s).
- [x] test(s) that actually pass.

### CODE REVIEW

**Comment by gotonode** [comment]
I think it's more intuitive now, but still not completely so. Or perhaps it's just me. 😄

Otherwise LGTM!

**Comment by gotonode** [comment]
I think one more person should review this before we merge. Does it seem intuitive to them as well?

**Comment by hisahi** [comment]
Also, the alternating background color is better as a light gray, as opposed to what it is now

**Comment by yumoL** [comment]
> The checkmark is always an X now, why? I set the points to 2, and it still says the maximum points don't match

The total points of checklist don't match because it's compared with the defaulted weekly points (which is 3).
So should we compare the total points of the checklist with the defaulted weekly points or the maximum points which the user defined himself?

**Comment by hisahi** [comment]
> > The checkmark is always an X now, why? I set the points to 2, and it still says the maximum points don't match
> 
> The total points of checklist don't match because it's compared with the defaulted weekly points (which is 3).
> So should we compare the total points of the checklist with the defaulted weekly points or the maximum points which the user defined himself?

To my knowledge, the comparison should be between the currently applied maximum points for the week, so the ones specified by the user *unless* none are specified, in which case it should compare to the default.

**Pull request merged**
